# Generated by Django 5.2.4 on 2025-07-16 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ajuste', models.CharField(max_length=20, verbose_name='Código do Ajuste/Empenho')),
                ('medicao_numero', models.IntegerField(verbose_name='Número da Medição')),
                ('nota_empenho_numero', models.CharField(max_length=35, verbose_name='Número da Nota de Empenho')),
                ('nota_empenho_data_emissao', models.DateField(verbose_name='Data de Emissão da Nota de Empenho')),
                ('documento_fiscal_numero', models.CharField(max_length=15, verbose_name='Número do Documento Fiscal (NF)')),
                ('documento_fiscal_uf', models.CharField(max_length=4, verbose_name='UF do Documento Fiscal (Ex: SP)')),
                ('documento_fiscal_valor', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor do Documento Fiscal')),
                ('documento_fiscal_data_emissao', models.DateField(verbose_name='Data de Emissão do Documento Fiscal')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ajuste', models.CharField(max_length=20, verbose_name='Código do Ajuste/Empenho')),
                ('medicao_numero', models.IntegerField(verbose_name='Número da Medição')),
                ('nota_empenho_numero', models.CharField(max_length=35, verbose_name='Número da Nota de Empenho')),
                ('nota_empenho_data_emissao', models.DateField(verbose_name='Data de Emissão da Nota de Empenho')),
                ('documento_fiscal_numero', models.CharField(max_length=15, verbose_name='Número do Documento Fiscal (NF)')),
                ('documento_fiscal_data_emissao', models.DateField(verbose_name='Data de Emissão do Documento Fiscal')),
                ('documento_fiscal_uf', models.CharField(max_length=4, verbose_name='UF do Documento Fiscal (Ex: SP)')),
                ('nota_fiscal_valor_pago', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor Pago da Nota Fiscal')),
                ('nota_fiscal_pagto_dt', models.DateField(verbose_name='Data Efetiva do Pagamento')),
                ('recolhido_encargos_previdenciario', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True, verbose_name='Recolhido Encargos Previdenciários?')),
            ],
        ),
    ]
