# Generated by Django 5.2.4 on 2025-07-16 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDocFiscalEmpenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ajuste', models.CharField(max_length=20, verbose_name='Código do Ajuste/Empenho')),
                ('medicao_numero', models.IntegerField(verbose_name='Número da Medição')),
                ('nota_empenho_numero', models.CharField(max_length=35, verbose_name='Número da Nota de Empenho')),
                ('nota_empenho_data_emissao', models.DateField(verbose_name='Data de Emissão da Nota de Empenho')),
                ('valor_parcela_do_empenho', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor da Parcela (deste Empenho) na NF')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalCabecalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_fiscal_numero', models.CharField(max_length=15, verbose_name='Número do Documento Fiscal (NF)')),
                ('documento_fiscal_uf', models.CharField(max_length=4, verbose_name='UF do Documento Fiscal (Ex: SP)')),
                ('documento_fiscal_data_emissao', models.DateField(verbose_name='Data de Emissão do Documento Fiscal')),
                ('documento_fiscal_valor_total', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Valor Total da Nota Fiscal')),
            ],
        ),
        migrations.DeleteModel(
            name='DocumentoFiscal',
        ),
        migrations.AddField(
            model_name='itemdocfiscalempenho',
            name='nota_fiscal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_empenho', to='core.notafiscalcabecalho'),
        ),
    ]
