"""
Django settings for audesp_generator project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w!q2&cg0o577y%(yf0^tx_q$3v6q3m_kq6rm^(xhzvxyiy0&j1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'audesp_generator.urls'

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os # Importar para usar os.path.join, se preferir

# ... (restante do seu settings.py, incluindo BASE_DIR) ...

# --- Configurações de TEMPLATES ---
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')], # Adiciona o diretório 'templates' na raiz do projeto
        'APP_DIRS': True, # Isso permite que o Django encontre templates dentro das pastas 'templates' de cada app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug', # Adicionado para debug, se útil
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_context',
            ],
        },
    },
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # <-- ESTA LINHA É FUNDAMENTAL!
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

WSGI_APPLICATION = 'audesp_generator.wsgi.application'

# ... (seção de DATABASE, PASSWORD_VALIDATION, INTERNATIONALIZATION) ...

# --- Configurações de STATIC FILES ---
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# URL para servir arquivos estáticos no desenvolvimento (ex: /static/admin/)
# --- Configurações de STATIC FILES ---
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # Pasta para collectstatic (produção)

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), # Onde seus arquivos estáticos DEVEM estar
]

# --- Configurações de MEDIA FILES (Opcional, para arquivos carregados por usuários) ---
# Se no futuro você precisar que os usuários façam upload de arquivos (ex: anexar documentos),
# você precisará dessas configurações. Se não for usar agora, pode ignorar.

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- Fim das configurações ---

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'